name: Deploy theme docs

on:
  push:
    branches:
      - master

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: restore node_modules
        uses: actions/cache@v2.1.5
        id: node-cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Get npm cache directory path
        if: steps.node-cache.outputs.cache-hit != 'true'
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: npm-cache
        if: steps.node-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v2.1.5
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Use npm v7
        run: sudo npm i -g npm@7

      - name: Install Deps
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm i

      - name: Build client
        run: npm run client:build

      - name: Build docs
        run: npm run docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: docs/.vuepress/dist
          ssh-key: ${{ secrets.SSH_TOKEN }}
          repository-name: walinejs/walinejs.github.io
